const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const classes = new Set();
const events = {};
const bar = {classList: {add: n => classes.add(n), remove: n => classes.delete(n)}, contains: () => false};
const document = {activeElement: {matches: () => false}, querySelector: s => s.includes('.mobile-bar') ? bar : null, addEventListener: (n, fn) => events[n] = fn};
const context = {window: {scrollY: 0}, document, addEventListener: (n, fn) => events[n] = fn, requestAnimationFrame: fn => fn()};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../assets/editorial-ui.js'), 'utf8'), context);
const scroll = y => {context.window.scrollY = y; events.scroll();};
const visible = () => classes.has('contact-visible');
assert.equal(visible(), false);
scroll(650); assert.equal(visible(), false);
scroll(640); assert.equal(visible(), false);
scroll(610); assert.equal(visible(), true);
scroll(650); assert.equal(visible(), false);
scroll(600); assert.equal(visible(), true);
document.activeElement.matches = () => true; events.focusin(); assert.equal(visible(), false);
document.activeElement.matches = () => false;
scroll(100); assert.equal(visible(), false);
console.log('PASS: contact bar hidden initially/downward, direction threshold, upward reveal, input focus and top-of-page hiding');
